In [6]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2 , 0.8, -0.5, 1.0]
weights2 = [0.5 , -0.91, 0.26, -0.5]
weights3 = [-0.26 , -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
          
print(output)

[4.8, 1.21, 2.385]


In [12]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2 , 0.8, -0.5, 1.0],
           [0.5 , -0.91, 0.26, -0.5],
           [-0.26 , -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

layer_outputs = [] #Output of current layer
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0 #Output of given neuron
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)
          
print(layer_outputs)

[4.8, 1.21, 2.385]


In [28]:
import numpy as np

inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2 , 0.8, -0.5, 1.0],
           [0.5 , -0.91, 0.26, -0.5],
           [-0.26 , -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

output  = np.dot(inputs, np.array(weights).T) + bias
print(output)

[[ 4.8    0.21   3.885]
 [ 8.9   -2.81   1.7  ]
 [ 1.41   0.051  1.526]]


In [31]:
import numpy as np

inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2 , 0.8, -0.5, 1.0],
           [0.5 , -0.91, 0.26, -0.5],
           [-0.26 , -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

weights2 = [[0.1 , -0.14, 0.5],
           [-0.5 , 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]


layer1_outputs  = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs  = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


## Main code start


In [44]:
import numpy as np

np.random.seed(0)

X = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)
layer3 = Layer_Dense(2,4)

layer1.forward(X)
print(layer1.output)
print(".....")
layer2.forward(layer1.output)
print(layer2.output)
print(".....")
layer3.forward(layer2.output)
print(layer3.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
.....
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
.....
[[ 0.00521944  0.00429504 -0.023497   -0.03947153]
 [ 0.00265117  0.00512263 -0.01416722 -0.02954161]
 [ 0.00565481  0.00647063 -0.02683625 -0.04862958]]


In [53]:
import numpy as np
import nnfs

nnfs.init()

X = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]

output = []

for i in inputs:
    output.append(max(0,i))
    
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [51]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [57]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data


nnfs.init()

X, y = spiral_data(100,3)

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        
layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)

#print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]]


In [79]:
import numpy as np
import nnfs

nnfs.init()

layer_outputs = [[4.8, 1.21, 2.385],
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]]

exp_values = np.exp(layer_outputs)

norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)
    
print(norm_values)

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [83]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities
        
X, y = spiral_data(samples=100, classes=3)
        
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()
        
dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()
        
dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.33331832 0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [90]:
import math

softmax_output = [0.7, 0.1, 0.2]

target_output = [1,0,0]

loss = -(math.log(softmax_output[0])*target_output[0] +
         math.log(softmax_output[1])*target_output[1]+
         math.log(softmax_output[2])*target_output[2])

print(loss)

loss = -math.log(softmax_output[0])
print(loss)

print(-math.log(0.7))
print(-math.log(0.5))

0.35667494393873245
0.35667494393873245
0.35667494393873245
0.6931471805599453
